version: '3.3'

services:
    s3:
        image: minio/minio:latest
        restart: unless-stopped
        ports:
            - "12348:9000"
            - "12349:9001"
        environment:
            - MINIO_ROOT_USER=<>
            - MINIO_ROOT_PASSWORD=<>
        command: server /data --console-address ":9001"
        networks:
            - internal
            - public
        volumes:
            - minio_volume:/data

    db:
        restart: always
        image: postgres:latest
        container_name: mlflow_db
        expose:
            - "5432"
        networks:
            - internal
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_DB=mlflowdb
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=sexample
        volumes:
            - db_datapg:/var/lib/postgresql/data

    app:
        restart: always
        build: .
        image: fahrengeit/mlflow_server:v2
        container_name: mlflow_server
        networks:
            - internal
            - public
        expose:
            - "12346"
        ports:
            - "12346:5000"
        environment:
            - BACKEND=postgresql://postgres:sexample@db:5432/mlflowdb
            - ARTIFACTS=s3://mlflow-artifacts/
            - MLFLOW_S3_ENDPOINT_URL=http://s3:9000
            - AWS_ACCESS_KEY_ID=<>
            - AWS_SECRET_ACCESS_KEY=<>
            - AWS_DEFAULT_REGION=us-east-1

        command:
            - sh    # (sh allows for var substitution of BACKEND and ARTIFACTS)
            - -c
            - mlflow server 
                --port 5000
                --host 0.0.0.0 
                --backend-store-uri $${BACKEND} 
                --default-artifact-root $${ARTIFACTS}
        depends_on:
            - db

networks:
    internal:
    public:
        driver: bridge

volumes:
    db_datapg:
    minio_volume: