version: '3.3'

services:
    db:
        restart: always
        image: postgres:latest
        container_name: mlflow_db
        expose:
            - "5432"
        networks:
            - mydefault
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_DB=mlflowdb
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=sexample
        volumes:
            - db_datapg:/var/lib/postgresql/data

    app:
        restart: always
        build: .
        image: fahrengeit/mlflow_server:v1
        container_name: mlflow_server
        networks:
            - mydefault
        expose:
            - "12346"
        ports:
            - "12346:5000"
        environment:
            - BACKEND=postgresql://postgres:sexample@db:5432/mlflowdb
            - ARTIFACTS=s3://adtech_mlflow_storage/artifacts/
            - MLFLOW_S3_ENDPOINT_URL=<some_link_here>
            - AWS_ACCESS_KEY_ID=<some_key_here>
            - AWS_SECRET_ACCESS_KEY=<some_secrete_key_here>
        volumes:
            - mlrun_data:/mlruns

        command:
            - sh    # (sh allows for var substitution of BACKEND and ARTIFACTS)
            - -c
            - mlflow server 
                --port 5000
                --host 0.0.0.0 
                --backend-store-uri $${BACKEND} 
                --default-artifact-root $${ARTIFACTS}
        depends_on:
            - db

networks:
    mydefault:
        driver: bridge

volumes:
    db_datapg:
    mlrun_data: